version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      - mongodb    
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - ifc-network 

  mongodb:
    image: mongo:5.0.5
    restart: always
    volumes:
      - ./.docker/dbdata:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=analytics
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - ifc-network      
  
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - mongodb
    networks:
      - ifc-network

  redis:
    image: redis:6.2.6-alpine3.14
    networks:
      - ifc-network

networks:
  ifc-network:
    name: ifc-network
    driver: bridge